apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: sparkclusters.radanalytics.io
spec:
  group: radanalytics.io
  versions:
    - name: v1
      served: true
      storage: true
  version: v1
  scope: Namespaced
  names:
    plural: sparkclusters
    singular: sparkcluster
    kind: SparkCluster
  validation:
    # openAPIV3Schema is the schema for validating custom objects.
    openAPIV3Schema:
      properties:
        master:
          type: object
          properties:
            instances:
              type: integer
              minimum: '1'
            memory:
              type: string
            cpu:
              type: string
            labels:
              type: string
              pattern: "([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]"
            command:
              type: array
              items:
                type: string
            commandArgs:
              type: array
              items:
                type: string
        worker:
          type: object
          properties:
            instances:
              type: integer
              minimum: '0'
            memory:
              type: string
            cpu:
              type: string
            labels:
              type: string
              pattern: "([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]"
            command:
              type: array
              items:
                type: string
            commandArgs:
              type: array
              items:
                type: string
        customImage:
          type: string
        metrics:
          type: boolean
        sparkWebUI:
          type: boolean
        sparkConfigurationMap:
          type: string
        env:
          type: array
          items:
            type: object
            javaType: io.radanalytics.types.Env
            properties:
              name:
                type: string
              value:
                type: string
            required:
              - name
              - value
        sparkConfiguration:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
              value:
                type: string
            required:
              - name
              - value
        labels:
          type: object
        historyServer:
          type: object
          properties:
            name:
              type: string
            type:
              type: string
              enum:
                - sharedVolume
                - remoteStorage
            sharedVolume:
              type: object
              properties:
                size:
                  type: string
                mountPath:
                  type: string
                matchLabels:
                  type: object
            remoteURI:
              type: string
              description: s3 bucket or hdfs path
        downloadData:
          type: array
          items:
            type: object
            properties:
              url:
                type: string
              to:
                type: string
            required:
              - url
              - to
      required: []
